// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: network_spec.proto

package burrow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hubs  uint32 `protobuf:"varint,1,opt,name=Hubs,proto3" json:"Hubs,omitempty"`
	Stops uint32 `protobuf:"varint,2,opt,name=Stops,proto3" json:"Stops,omitempty"`
	// Types that are assignable to Distribution:
	//
	//	*NetworkSpec_Uniform
	//	*NetworkSpec_Gaussian
	Distribution isNetworkSpec_Distribution `protobuf_oneof:"Distribution"`
	Start        *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	End          *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=end,proto3" json:"end,omitempty"`
	ShortEdge    *durationpb.Duration       `protobuf:"bytes,7,opt,name=ShortEdge,proto3" json:"ShortEdge,omitempty"`
	LongEdge     *durationpb.Duration       `protobuf:"bytes,8,opt,name=LongEdge,proto3" json:"LongEdge,omitempty"`
}

func (x *NetworkSpec) Reset() {
	*x = NetworkSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_spec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec) ProtoMessage() {}

func (x *NetworkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_network_spec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec.ProtoReflect.Descriptor instead.
func (*NetworkSpec) Descriptor() ([]byte, []int) {
	return file_network_spec_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkSpec) GetHubs() uint32 {
	if x != nil {
		return x.Hubs
	}
	return 0
}

func (x *NetworkSpec) GetStops() uint32 {
	if x != nil {
		return x.Stops
	}
	return 0
}

func (m *NetworkSpec) GetDistribution() isNetworkSpec_Distribution {
	if m != nil {
		return m.Distribution
	}
	return nil
}

func (x *NetworkSpec) GetUniform() *NetworkSpec_UniformDistro {
	if x, ok := x.GetDistribution().(*NetworkSpec_Uniform); ok {
		return x.Uniform
	}
	return nil
}

func (x *NetworkSpec) GetGaussian() *NetworkSpec_GaussianDistro {
	if x, ok := x.GetDistribution().(*NetworkSpec_Gaussian); ok {
		return x.Gaussian
	}
	return nil
}

func (x *NetworkSpec) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *NetworkSpec) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *NetworkSpec) GetShortEdge() *durationpb.Duration {
	if x != nil {
		return x.ShortEdge
	}
	return nil
}

func (x *NetworkSpec) GetLongEdge() *durationpb.Duration {
	if x != nil {
		return x.LongEdge
	}
	return nil
}

type isNetworkSpec_Distribution interface {
	isNetworkSpec_Distribution()
}

type NetworkSpec_Uniform struct {
	Uniform *NetworkSpec_UniformDistro `protobuf:"bytes,3,opt,name=Uniform,proto3,oneof"`
}

type NetworkSpec_Gaussian struct {
	Gaussian *NetworkSpec_GaussianDistro `protobuf:"bytes,4,opt,name=Gaussian,proto3,oneof"`
}

func (*NetworkSpec_Uniform) isNetworkSpec_Distribution() {}

func (*NetworkSpec_Gaussian) isNetworkSpec_Distribution() {}

type NetworkSpec_UniformDistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NetworkSpec_UniformDistro) Reset() {
	*x = NetworkSpec_UniformDistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_spec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSpec_UniformDistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec_UniformDistro) ProtoMessage() {}

func (x *NetworkSpec_UniformDistro) ProtoReflect() protoreflect.Message {
	mi := &file_network_spec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec_UniformDistro.ProtoReflect.Descriptor instead.
func (*NetworkSpec_UniformDistro) Descriptor() ([]byte, []int) {
	return file_network_spec_proto_rawDescGZIP(), []int{0, 0}
}

type NetworkSpec_GaussianDistro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mean   int64 `protobuf:"varint,1,opt,name=Mean,proto3" json:"Mean,omitempty"`
	StdDev int64 `protobuf:"varint,2,opt,name=StdDev,proto3" json:"StdDev,omitempty"`
}

func (x *NetworkSpec_GaussianDistro) Reset() {
	*x = NetworkSpec_GaussianDistro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_network_spec_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSpec_GaussianDistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSpec_GaussianDistro) ProtoMessage() {}

func (x *NetworkSpec_GaussianDistro) ProtoReflect() protoreflect.Message {
	mi := &file_network_spec_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSpec_GaussianDistro.ProtoReflect.Descriptor instead.
func (*NetworkSpec_GaussianDistro) Descriptor() ([]byte, []int) {
	return file_network_spec_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NetworkSpec_GaussianDistro) GetMean() int64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *NetworkSpec_GaussianDistro) GetStdDev() int64 {
	if x != nil {
		return x.StdDev
	}
	return 0
}

var File_network_spec_proto protoreflect.FileDescriptor

var file_network_spec_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xeb, 0x03, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x48, 0x75, 0x62, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x48,
	0x75, 0x62, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x53, 0x74, 0x6f, 0x70, 0x73, 0x12, 0x3f, 0x0a, 0x07, 0x55, 0x6e, 0x69,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x75, 0x74,
	0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x70, 0x65,
	0x63, 0x2e, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x48,
	0x00, 0x52, 0x07, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x42, 0x0a, 0x08, 0x47, 0x61,
	0x75, 0x73, 0x73, 0x69, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74,
	0x75, 0x74, 0x6f, 0x72, 0x69, 0x61, 0x6c, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x47, 0x61, 0x75, 0x73, 0x73, 0x69, 0x61, 0x6e, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x48, 0x00, 0x52, 0x08, 0x47, 0x61, 0x75, 0x73, 0x73, 0x69, 0x61, 0x6e, 0x12, 0x30,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x2c, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x37,
	0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x45, 0x64, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x4c, 0x6f, 0x6e, 0x67, 0x45,
	0x64, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x4c, 0x6f, 0x6e, 0x67, 0x45, 0x64, 0x67, 0x65, 0x1a, 0x0f,
	0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x1a,
	0x3c, 0x0a, 0x0e, 0x47, 0x61, 0x75, 0x73, 0x73, 0x69, 0x61, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x72,
	0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x65, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x4d, 0x65, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x64, 0x44, 0x65, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53, 0x74, 0x64, 0x44, 0x65, 0x76, 0x42, 0x0e, 0x0a,
	0x0c, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1d, 0x5a,
	0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x64, 0x73, 0x68,
	0x72, 0x6f, 0x79, 0x65, 0x72, 0x2f, 0x62, 0x75, 0x72, 0x72, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_network_spec_proto_rawDescOnce sync.Once
	file_network_spec_proto_rawDescData = file_network_spec_proto_rawDesc
)

func file_network_spec_proto_rawDescGZIP() []byte {
	file_network_spec_proto_rawDescOnce.Do(func() {
		file_network_spec_proto_rawDescData = protoimpl.X.CompressGZIP(file_network_spec_proto_rawDescData)
	})
	return file_network_spec_proto_rawDescData
}

var file_network_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_network_spec_proto_goTypes = []interface{}{
	(*NetworkSpec)(nil),                // 0: tutorial.NetworkSpec
	(*NetworkSpec_UniformDistro)(nil),  // 1: tutorial.NetworkSpec.UniformDistro
	(*NetworkSpec_GaussianDistro)(nil), // 2: tutorial.NetworkSpec.GaussianDistro
	(*timestamppb.Timestamp)(nil),      // 3: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 4: google.protobuf.Duration
}
var file_network_spec_proto_depIdxs = []int32{
	1, // 0: tutorial.NetworkSpec.Uniform:type_name -> tutorial.NetworkSpec.UniformDistro
	2, // 1: tutorial.NetworkSpec.Gaussian:type_name -> tutorial.NetworkSpec.GaussianDistro
	3, // 2: tutorial.NetworkSpec.start:type_name -> google.protobuf.Timestamp
	3, // 3: tutorial.NetworkSpec.end:type_name -> google.protobuf.Timestamp
	4, // 4: tutorial.NetworkSpec.ShortEdge:type_name -> google.protobuf.Duration
	4, // 5: tutorial.NetworkSpec.LongEdge:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_network_spec_proto_init() }
func file_network_spec_proto_init() {
	if File_network_spec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_network_spec_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_spec_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSpec_UniformDistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_network_spec_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSpec_GaussianDistro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_network_spec_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NetworkSpec_Uniform)(nil),
		(*NetworkSpec_Gaussian)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_network_spec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_spec_proto_goTypes,
		DependencyIndexes: file_network_spec_proto_depIdxs,
		MessageInfos:      file_network_spec_proto_msgTypes,
	}.Build()
	File_network_spec_proto = out.File
	file_network_spec_proto_rawDesc = nil
	file_network_spec_proto_goTypes = nil
	file_network_spec_proto_depIdxs = nil
}
