name: burrow-test
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go mod tidy
      - run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - run: ginkgo -r
