name: burrow-benchmark
on: workflow_dispatch
jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go mod tidy
      - run: go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
      - run: cd benchmarks && ginkgo
